### ISSUE TITLE
Filter on property "ean" is not supported or does not support operator "NOT EMPTY"

### ISSUE THREAD

**Issue by igormukhingmailcom** [akeneo/IcecatConnector#31]
Hi, guys.

Having next issue:

```
Error #0 in class Pim\Component\Catalog\Exception\UnsupportedFilterException: Filter on property "ean" is not supported or does not support operator "NOT EMPTY"
```

Notes:
- `Akeneo 1.7`
- `IceCatConnector 1.2.2 `
- `ean` attribute have `pim_catalog_identifier` type (and so `unique` flag as `true`)
- Removing next lines at `Pim\Bundle\IcecatConnectorBundle\Reader\ProductReader` fixing issue:
```
        $filters[] = [
            'field'    => $this->eanAttributeCode,
            'operator' => Operators::IS_NOT_EMPTY,
            'value'    => null,
        ];
```

**Comment by jmleroux** [comment]
This one is not normal: a `pim_identifier` attribute should (must) support the non-empty filter.
I'll check with my core teammates.

**Comment by jmleroux** [comment]
I just tested with EAN `8806088281285` and it works normally.

![image](https://user-images.githubusercontent.com/1516770/32954683-17c705a8-cbb4-11e7-9986-e8b4d6b0d275.png)
