### ISSUE TITLE
An exception occured in icecat_enrich

### ISSUE THREAD

**Issue by FatalCaca** [akeneo/IcecatConnector#46]
Hello,

We started using the Icecat connector a few days ago. The mapping with our attributes is done and ok
We encounter a problem when starting the job `icecat_enrich`

It doesn's seem to go very far and throws a "An exception occured during the job execution" almost instantly :
![image](https://user-images.githubusercontent.com/5050188/34029322-f7968e68-e178-11e7-8695-f64beb519191.png)

Our product base is currently just a sample. We took a few EAN from the icecat catalog which we imported via the csv import
![image](https://user-images.githubusercontent.com/5050188/34029358-2eb28b18-e179-11e7-98de-b071328f94a4.png)

Is there any way I can get a more detailed report on the exception encountered ? The monolog log is quite verbose but dont really show any info about the exception except the recording of the message "An exception occured ..." and a "No route found" error which I doubt is related 
`[2017-12-15 07:22:54] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /collect/import/import_produits_csv/_wdt/63aec6"`

**Comment by jmleroux** [comment]
Hello,
this route is related to the Symfony profiler. Could you try to execute the job in a prod env?

Regards,
JM

**Comment by FatalCaca** [comment]
Thank you for your answer :)

Same thing in prod env
I'm able to get this error when starting the job in console (I'm quite a beginner with akeneo) :

```
./app/console akeneo:batch:job icecat_enrich -vvv
[2017-12-15 13:45:26] batch.DEBUG: Job execution starting: startTime=, endTime=, updatedTime=, status=2, exitStatus=[UNKNOWN] , exitDescription=[], job=[icecat_enrich] [] []
[2017-12-15 13:45:26] batch.INFO: Step execution starting: id=0, name=[import], status=[2], exitCode=[EXECUTING], exitDescription=[] [] []

                                                                                                                        
  [Symfony\Component\Debug\Exception\UndefinedMethodException]                                                          
  Attempted to call an undefined method named "setTextCollection" of class "Pim\Component\Catalog\Model\ProductValue".  
                                                                                                                        

Exception trace:
 () at /var/www/html/akeneo/vendor/akeneo/pim-community-dev/src/Pim/Component/Catalog/Model/AbstractProductValue.php:285
 Pim\Component\Catalog\Model\AbstractProductValue->setData() at /var/www/html/akeneo/vendor/akeneo/extended-attribute-type/src/Updater/Setter/TextCollectionAttributeSetter.php:75
 Pim\Bundle\ExtendedAttributeTypeBundle\Updater\Setter\TextCollectionAttributeSetter->setData() at /var/www/html/akeneo/vendor/akeneo/extended-attribute-type/src/Updater/Setter/TextCollectionAttributeSetter.php:48
 Pim\Bundle\ExtendedAttributeTypeBundle\Updater\Setter\TextCollectionAttributeSetter->setAttributeData() at /var/www/html/akeneo/vendor/akeneo/pim-community-dev/src/Pim/Component/Catalog/Updater/ProductPropertySetter.php:61
 Pim\Component\Catalog\Updater\ProductPropertySetter->setData() at /var/www/html/akeneo/vendor/akeneo/pim-community-dev/src/Pim/Component/Catalog/Updater/ProductUpdater.php:180
 Pim\Component\Catalog\Updater\ProductUpdater->updateProductValues() at /var/www/html/akeneo/vendor/akeneo/pim-community-dev/src/Pim/Component/Catalog/Updater/ProductUpdater.php:135
 Pim\Component\Catalog\Updater\ProductUpdater->update() at /var/www/html/akeneo/vendor/akeneo/icecat-connector/src/Enrich/EnrichProductProcessor.php:99
 Pim\Bundle\IcecatConnectorBundle\Enrich\EnrichProductProcessor->process() at /var/www/html/akeneo/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Step/ItemStep.php:173
 Akeneo\Component\Batch\Step\ItemStep->process() at /var/www/html/akeneo/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Step/ItemStep.php:119
 Akeneo\Component\Batch\Step\ItemStep->doExecute() at /var/www/html/akeneo/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Step/AbstractStep.php:100
 Akeneo\Component\Batch\Step\AbstractStep->execute() at /var/www/html/akeneo/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Job/Job.php:263
 Akeneo\Component\Batch\Job\Job->handleStep() at /var/www/html/akeneo/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Job/Job.php:226
 Akeneo\Component\Batch\Job\Job->doExecute() at /var/www/html/akeneo/vendor/akeneo/pim-community-dev/src/Akeneo/Component/Batch/Job/Job.php:160
 Akeneo\Component\Batch\Job\Job->execute() at /var/www/html/akeneo/vendor/akeneo/pim-community-dev/src/Akeneo/Bundle/BatchBundle/Command/BatchCommand.php:161
 Akeneo\Bundle\BatchBundle\Command\BatchCommand->execute() at /var/www/html/akeneo/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:261
 Symfony\Component\Console\Command\Command->run() at /var/www/html/akeneo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:857
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/akeneo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:188
 Symfony\Component\Console\Application->doRun() at /var/www/html/akeneo/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:90
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/akeneo/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:119
 Symfony\Component\Console\Application->run() at /var/www/html/akeneo/app/console:29
```

Could this be a missing attribute in our database ?

I also investigated a little bit and it seems that the guzzle result of the icecat query returns nothing
line 98 of `src/Enrich/EnrichProductProcessor.php`
If I `var_dump($res->getBody()->getContents())` it gives an empty string

**Comment by jmleroux** [comment]
I think you didn't overide the `ProductValue` entity and so there is no method to set the TextCollection.
It is part of the ExtendedAttributre documentation, but I should add it to this bundle documentation.
You can find the documentation here: https://github.com/akeneo/ExtendedAttributeTypeBundle/blob/1.0/doc/index.md#create-the-new-productvalue-model

**Comment by FatalCaca** [comment]
It was indeed the `ProductValue` not being overriden :)

The import seems to start correctly now, but the report is filled with warning such as 
![image](https://user-images.githubusercontent.com/5050188/34068670-68f8cdb4-e250-11e7-97a7-068c49c43815.png)

This specific line is about this product https://icecat.fr/p/lexmark/10d2692/multifonctions-0734646512640-Lexmark-MX912dxe-1200-x-1200DPI-Laser-A3-65ppm-37611474.html

This product in our akeneo :
![image](https://user-images.githubusercontent.com/5050188/34068855-79488e26-e254-11e7-8c02-d2abd10c29de.png)

I can see that a `ProductValue` has been created in db but it's empty
![image](https://user-images.githubusercontent.com/5050188/34068860-a0a56336-e254-11e7-8fc9-c3bf182b7299.png)

(I don't know If I should create a new issue for this ?)

**Comment by FatalCaca** [comment]
I think I found it
It's `Pim\Bundle\IcecatConnectorBundle\Mapping\AttributeMapper::loadMapping` that screwed up
The `mapping.csv` that was loaded had a comma delimiter. loadMapping read it as with a semicolumn delimiter. I just added a delimiter detection :

```
    protected function loadMapping()
    {
        $mappingFilePath = '/tmp/mapping.csv';

        if (!file_exists($mappingFilePath)) {
            throw new MapperException(
                sprintf('Mapping file "%s" does not exists', $mappingFilePath),
                MapperException::FILE_NOT_FOUND
            );
        }
        $fileHandle = fopen($mappingFilePath, 'r');

        **$splFile = new \SplFileObject($mappingFilePath);
        $csvDelimiter = $splFile->getCsvControl()[0];**

        // skip headers
        fgetcsv($fileHandle, 0, $csvDelimiter);

        $mapping = [];
        while ($row = fgetcsv($fileHandle, 0, $csvDelimiter)) {
            list($icecatId, $pimCode) = $row;
            $mapping[$icecatId] = $pimCode;
        }

        return $mapping;
    }
```

I still have some issue but I think they are due to our mapping and not to a bug

**Comment by jmleroux** [comment]
Thank you for the good diagnostic work! :+1:
